name: CI
on:
  push:
    branches:
      - master
      - for-master
    tags:
      - v*
  pull_request:
    branches:
      - master
      - for-master
jobs:
  build:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
      fail-fast: false

    runs-on: ${{ matrix.os }}
    steps:

    - name: Checkout
      uses: actions/checkout@v6

    - name: Build
      run: |
        ./configure
        make

    - name: Test
      run: |
        make test
